#!/bin/bash
sudo virsh shutdown bootstrap.ocp4.nico.coffee

for i in {1..3}; do
	sudo virsh shutdown master0${i}.ocp4.nico.coffee
	sudo virsh shutdown worker0${i}.ocp4.nico.coffee
done

sudo virsh shutdown bastion.nico.coffee

